ROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app .

# Expone puerto
EXPOSE 3000

# Ajusta la variable de entorno
ENV NODE_ENV=production

# Comando de arranque
CMD ["node", "src/index.js"]