version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: todo-api:prod
    container_name: todo-api-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production 
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:15-alpine
    container_name: todo-db-prod
    restart: always
    env_file:
      - .env.production
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data

volumes:
  prod_postgres_data:
