version: "3.8"

services:
  api:
    build: .
    container_name: todo-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: camilo
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
